# Generated by Django 4.2.6 on 2023-10-30 19:56

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('anketa', '0002_naviki'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myuser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('title', models.TextField(max_length=50, verbose_name='Пользователь')),
                ('phonenumber', models.TextField(max_length=50, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Гражданин',
                'verbose_name_plural': 'Граждане',
                'ordering': ['-title'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PystoiSertificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Название сертификата')),
                ('full', models.ImageField(blank=True, upload_to='PystoiSertificat/%Y/%m/%d')),
                ('one', models.ImageField(blank=True, upload_to='PystoiSertificat/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Пустой сертификат',
                'verbose_name_plural': 'Пустые сертификаты',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Vopros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Текст вопроса')),
                ('ball', models.IntegerField(default=0, verbose_name='Балл')),
                ('naviki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voprosnaviki', to='anketa.naviki')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Model_prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Название')),
                ('ball', models.PositiveIntegerField()),
                ('Naviki', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anketa.naviki', verbose_name='Навык')),
                ('Proffessia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anketa.proffessia', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Модельная профессия',
                'verbose_name_plural': 'Модельные профессии',
                'ordering': ['-title'],
            },
        ),
    ]
